#!/bin/bash


# data.sh declares all variables and data required for djinn and its derivative scripts
source $NRT_WS/scripts/helpers/data.sh
# exec.sh declares all execution functions required for djinn and its derivative scripts
source $NRT_WS/scripts/helpers/exec.sh

build_image(){
	if [[ -z "$(docker images -q $2 2> /dev/null)" ]]
	then
		if [[ "$(docker manifest inspect $2 > /dev/null 2>&1 && echo yes || echo no)" == "no" ]]
		then
			$NRT_WS/docker/scripts/docker-build.sh $1 $2 $3 $4 
		else
			docker pull $2
		fi
	fi
}

cd $NRT_WS

if [[ "$1" == "install" ]]
then
	scripts/install.sh $2 $3 $4


elif [[ "$1" == "init" ]]
then
	if [[ ! -d ".ssh" ]]
	then
		read -p "Enter email address for github: " email
		read -p "Enter username for dockerhub: " name
		echo "VERSION=0.0.4" >> $config_file
		echo "ROS_VERSION=\"humble\"" >> $config_file
		echo "userEmail="$email >> $config_file 
		echo "userName="$name >> $config_file 
		if [[ -d "$HOME/.ssh" && ! -L "${HOME}/.ssh" ]]
		then
			cp -r "$HOME/.ssh" $NRT_WS/.ssh
		else
			mkdir .ssh 
			cd .ssh
			ssh-keygen -q -t rsa -C "$email" -N "" -f id_rsa <<<y >/dev/null 2>&1
			cd -
		fi
	fi
	export $(grep -v '^#' $config_file | xargs)
	echo "Github Email: $userEmail"
	echo "Dockerhub ID: $userName"
	if [[ "$2" == "docker" ]]
	then
		platform="linux/amd64,linux/arm64"
		mode="base"
		echo "$3"
		if [[ -n "$3" ]]
		then
			echo "============ BUILDING Image ============="
			if [[ "$3" == "nrt" ]]
			then
				echo "============ BUILDING Base Image ============="
				image="$userName/nrt:base"
				filepath="$NRT_WS/docker/base/"
				build_image $platform $image $filepath
				echo "============ BUILDING ROS Image ============="
				image="$userName/nrt:ros"
				filepath="$NRT_WS/docker/base/ros"
				platform="linux/amd64,linux/arm64"
				build_image $platform $image $filepath 
				echo "============ BUILDING NRT Pangolin Image ============="
				image="$userName/nrt:pangolin"
				filepath="$NRT_WS/docker/nrt/pangolin"
				platform="linux/amd64,linux/arm64"
				build_image $platform $image $filepath 
				echo "============ BUILDING NRT VERSION:$VERSION Image ============="
				image="$userName/nrt:$VERSION"
				filepath="$NRT_WS/docker/nrt/camera"
				platform="linux/amd64,linux/arm64"
				container_name="nrt_container"
				build_image $platform $image $filepath 
				echo "============ BUILDING SIMULATION Image ============="
				cd $WS_PATH/envs/ue5/AirSim/docker/
				python3 build_airsim_image.py --source --target_image="shandilya1998/nrt_airsim:0.0.1"
				cd -	
				source $NRT_WS/scripts/start.sh "$NRT_WS" "$container_name" "$image"
                iexec nrt_container "ls && echo \"Starting Container Setup\" && /ws/docker/scripts/docker-setup.sh $3 $userEmail $userName"
				if [[ ! -f "ext/QGroundControl.AppImage" ]]
				then
					iexec nrt_container "wget https://d176tv9ibo4jno.cloudfront.net/latest/QGroundControl.AppImage -O /ws/ext/QGroundControl.AppImage"
					iexec nrt_container "chmod +x /ws/ext/QGroundControl.AppImage"
				fi
			elif [[ "$3" == "airsim"  ]]
			then
				echo "============ BUILDING SIMULATION Image ============="
				cd $NRT_WS/envs/ue5/AirSim/docker/
				python3 build_airsim_image.py --source --target_image="shandilya1998/nrt_airsim:0.0.1"
				cd -
			elif [[ "$3" == "ardupilot" ]]
			then
				# ensure this command is run after the `djinn init docker nrt` has been successfully run
				image_base="shandilya1998/nrt_ardupilot:base"
				filepath_base="ext/ardupilot/"
				image="shandilya1998/nrt_ardupilot:0.0.1"
				filepath="docker/ardupilot"
				platform="linux/amd64"
				if [[ ! -d "$filepath_base" ]]
				then
					echo "ArduPilot does not exist, so cloning the repository"
					cd $NRT_WS/ext
					git clone git@github.com:ArduPilot/ardupilot.git
					cd ardupilot
					git submodule update --init --recursive
					cd $NRT_WS
				else
					echo "ArduPilot exits no need to clone"
				fi
				if [[ -n "$4" ]]
				then
					if [[ "$4" == "aarch64"  ]]
					then
						platform="linux/arm64"
					elif [[ "$4" == "x86_64" ]]
					then
						platform="linux/amd64"
					elif [[ "$4" == "all" ]]
					then
						platform="linux/amd64,linux/arm64"
					else
						echo "unsupported platform"
						cd $WS_PATH
						exit
					fi
				fi
				build_image $platform $image_base $filepath_base "NRT_WS=$NRT_WS"
				build_image $platform $image $filepath "NRT_WS=$NRT_WS"
				docker run -it --rm -d -v $NRT_WS/ext/ardupilot:/ardupilot --name ardupilot_init_container $image bash
				iexec ardupilot_container "cd /ardupilot && git checkout Copter-4.5.7"
				iexec ardupilot_container "cd /ardupilot && git submodule update --init --recursive"
				iexec ardupilot_init_container "cd /ardupilot && ./waf configure --board sitl && ./waf copter"
				docker stop ardupilot_init_container
			elif [[ "$3" == "kalibr" ]]
			then
				echo "============ BUILDING Kalibr Image ============="
				image="$userName/nrt:kalibr"
				filepath="$NRT_WS/ext/calibration/kalibr/"
				container_name="kalibr_container"
				mode="kalibr"
				build_image $platform $image $filepath "NRT_WS=$NRT_WS"
			fi
		fi
	fi

elif [[ "$1" == "up" ]]
then
	mode="ros"
	export $(grep -v '^#' $config_file | xargs)
	echo "username: $userName"
	echo "email: $userEmail"
	# git submodule update --init --recursive
	if [[ -n "$2" ]]
	then
		
		if [[ "$2" == "nrt"  ]]
		then
			echo "=============== Initialising NRT Base Container ================"
			source $NRT_WS/scripts/start.sh $NRT_WS nrt_container shandilya1998/nrt:$VERSION
			iexec_ros nrt_container "ls && echo \"Starting Container Setup\" && /ws/scripts/docker-setup.sh $2 $userEmail $userName" 
			iexec_ros nrt_container "/ws/scripts/build_ros_packages.sh"
		elif [[ "$2" == "airsim" ]]
		then
			xhost +local:docker
			cd $NRT_WS/envs/ue5/AirSim/docker/
 			source $NRT_WS/envs/ue5/scripts/start.sh $NRT_WS/envs/ue5/AirSim/Unreal/Environments
			cd -
		elif [[ "$2" == "ardupilot" ]]
		then
			# assuming that currently we are only building for drones
			docker run --rm --net=host --privileged -it -d -v $NRT_WS:/ws -v $NRT_WS/ext/ardupilot:/ardupilot --name ardupilot_container shandilya1998/nrt_ardupilot:0.0.1 bash
			iexec ardupilot_container "cd /ardupilot && git checkout Copter-4.5.7"
			iexec ardupilot_container "cd /ardupilot && git submodule update --init --recursive"
			iexec ardupilot_container "cd /ardupilot && ./waf configure --board sitl && ./waf copter"
		elif [[ "$2" == "kalibr" ]]
		then
			echo "============ Initialising Kalibr Container ============="
			source $NRT_WS/scripts/start.sh $NRT_WS kalibr_container shandilya1998/nrt:kalibr
		fi
	else
		source $NRT_WS/scripts/start.sh $NRT_WS nrt_container shandilya1998/nrt:$VERSION
		iexec_ros nrt_container "ls && echo \"Starting Container Setup\" && /ws/scripts/docker-setup.sh $2 $userEmail $userName" 
		iexec_ros nrt_container "./scripts/build.sh && ./scripts/build_ros_packages.sh && cd ros_ws && source install/local_setup.bash && cd .."
	fi

elif [[ "$1" == "build" ]]
then	
	clear
	if [[ -z "$2" ]]
	then
		echo "=========== BUILDING NRT And related Packages ==========="
		
		iexec_ros nrt_container "./scripts/build.sh && ./scripts/build_ros_packages.sh && cd ros_ws && source install/local_setup.bash && cd .."
	else
		if [[  "$2" == "nrt" ]]
		then
			echo "=========== BUILDING Packages ==========="
			echo $PWD
			iexec_ros nrt_container "./scripts/build_ros_packages.sh"
		elif [[ "$2" == "docker" ]]
		then
			image="$3"
			filepath="$4"
			platform="linux/amd64,linux/arm64"
			if [[ -n "$5" ]]
			then
				if [[ "$5" == "aarch64"  ]]
				then
					platform="linux/arm64"
				elif [[ "$5" == "x86_64" ]]
				then
					platform="linux/amd64"
				elif [[ "$5" == "all" ]]
				then
					platform="linux/amd64,linux/arm64"
				else
					echo "unsupported platform"
					cd $WS_PATH
					exit
				fi
			fi
			# build_image $platform $image $filepath "NRT_WS=$NRT_WS"
			source $NRT_WS/docker/scripts/docker-build.sh $platform $image $filepath "NRT_WS=$NRT_WS" 
		fi
	fi

elif [[  "$1" == "exec" ]]
then
	# djinn exec "cd ros_ws/src/ && ros2 pkg create --build-type ament_cmake Sensors" for creating ros2 packages
	# echo "${2}_container"
	if [[ "$2" == "nrt" ]]
	then
		iexec_ros "${2}_container" $3
	else
		iexec "${2}_container" "$3"
	fi

elif [[  "$1" == "start" ]]
then
	if [[ "$2" == "tello" ]]
	then
		iexec_ros nrt_container "source /ws/ros_ws/install/setup.bash && ros2 launch controllers tello_launch.py"
	elif [[ "$2" == "tello-orbslam3" ]]
	then
		iexec_ros nrt_container "source /ws/ros_ws/install/setup.bash && ros2 launch controllers tello_orbslam3_mono_launch.py"
	elif [[ "$2" == "sitl" ]]
	then
		echo "starting sitl"
		gnome-terminal --title "AirSim" -- bash -c "$NRT_WS/envs/ue5/scripts/run_airsim.sh; exec bash"
		gnome-terminal --title "ArduPilot" -- bash -c "$NRT_WS/envs/scripts/run_ardupilot.sh; exec bash"
	fi

elif [[ $1 == "kill" ]]
then
	echo "Killing running proceses"
	if [[ "$2" == "sitl" ]]
	then
		echo "Killing SITL processes"
		iexec sitl_container "ps -eawf | grep NRT | grep -v grep | awk '{print \$2}' | xargs -r kill -9"
		# ps -ef | grep QGroundControl | grep -v grep | awk '{print $2}' | xargs -r kill -9
		if [[ ! -z "$last_run_sitl_env"  ]]
		then
			ps -eawf | grep "$last_run_sitl_env" | grep -v grep | awk '{print $2}' | xargs -r kill -9
		fi
		echo "Done Killing SITL processes"
	elif [[ $2 == "airsim" ]]
	then
		if [[ ! -z "$last_run_sitl_env"  ]]
		then
			ps -eawf | grep "$last_run_sitl_env" | grep -v grep | awk '{print $2}' | xargs -r kill -9
		fi
		iexec nrt_container "ps -eawf | grep airsim_lib | grep -v grep | awk '{print \$2}' | xargs -r kill -9"
	elif [[ "$2" == "gqc" ]]
	then
		ps -ef | grep QGroundControl | grep -v grep | awk '{print $2}' | xargs -r kill -9
	fi

elif [[ "$1" == "down" ]]
then
	if [[ -n "$2" ]]
	then
		docker stop "${2}_container"
	else
		docker stop base_container nrt_container sitl_container vision_tools_container bfx_container
	fi

elif [[ "$1" == "rmi" ]]
then
	if [[ -n "$2" ]]
	then
		if [[ "$2" == "all" ]]
		then
			docker images | grep -v grep |  tail -n +2 |  awk '{print $3}'  | xargs -r docker rmi -f
		else
			docker rmi -f "$2"
		fi
	fi

elif [[ "$1" == "ps" ]]
then
	docker ps

elif [[ "$1" == "search" ]]
then
	grep -inr --include \*.h \
		--include \*.cpp \
		--include \*.hpp \
		--include \*.py \
		--include \*CMakeLists.txt \
		--include \*.sh \
		--include \*package.xml "$2" \
		--include $NRT_WS/djinn	-e "$3"
fi
